1	KehnaHiKya	USSDSSDUS
2	Kalank		SUSDSSDUS
3	BadtameezDil	UDSDSSDUS
4	Safar		DDDDSSSUD
5	PhiLeAyaDil	SDUDUSSDD
6	Ghoomar		DUSUDSDSS
7	TereMitti	DUSUDSDSS
8	TuHaiKiNahi	UDSDSSDUD
9	Kabira		UDSDDDDUS
10	OhSanam		UDDDSSSUS
11	TeaSuit		USSDSSDUD
12	BaarishBanJaan	USSDUSDUS
13	PaaniPaani	SUSDSSDUS
14	BaarishKiJaye	SDSDSSDUS
15	IsQadar		SUSDDSDUS
16	NainoLagna	SUSDSSDUU
17	DoobGaye	DUSDSSDUS
18	AjabSi		DSSDSSDUS
19	TujhMeinRabDikhtaHai	DSUDSUUDD
20	ChannaMereya		DSUDSUUDS






